# -*- coding: utf-8 -*-
"""Copy of etri_skeleton_classifier_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Um1Z2iR-Oq_e2vIS6atfEiu-PEDM2qc0

Extract the dataset
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile, os

zip_path = "/content/drive/MyDrive/ETRI-Activity3D_CSV.zip"
os.makedirs("etri_csv_data", exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall("etri_csv_data")

for root, dirs, files in os.walk("etri_csv_data"):
    print(root, files[:5])

import subprocess
subprocess.run(["pip", "install", "pandas", "numpy", "scikit-learn", "tensorflow", "matplotlib", "seaborn", "-q"], check=True)

"""## Loading, normalization, and feature-engineering functions"""

import numpy as np
import pandas as pd
import glob, os, re
import tensorflow as tf

def get_joint_columns_with_tracking():
    cols = ["frameNum"]
    for j in range(1, 26):
        cols += [f"joint{j}_3dX", f"joint{j}_3dY", f"joint{j}_3dZ", f"joint{j}_trackingState"]
    return cols

JOINT_COLS_TRACK = get_joint_columns_with_tracking()

def parse_filename(fname):
    match = re.match(r"A(\d+)_P(\d+)_G(\d+)_C(\d+)", os.path.basename(fname))
    if match:
        action, person, group, camera = match.groups()
        return int(action), int(person), int(group), int(camera)
    return None

def load_skeleton_csv_clean(path):
    df = pd.read_csv(path, usecols=JOINT_COLS_TRACK)
    df = df.sort_values("frameNum").reset_index(drop=True)

    coords_list = []
    for j in range(1, 26):
        xyz = df[[f"joint{j}_3dX", f"joint{j}_3dY", f"joint{j}_3dZ"]].values.astype(np.float32)  # was float64
        tracking = df[f"joint{j}_trackingState"].values

        xyz[tracking == 0] = np.nan
        xyz_df = pd.DataFrame(xyz).ffill().bfill().fillna(0)
        coords_list.append(xyz_df.values.astype(np.float32))
    coords = np.concatenate(coords_list, axis=1)
    return coords

def normalize_skeleton(coords):
    """
    Centers each frame on joint1 (SpineBase) and scales by torso length
    (SpineBase to SpineShoulder), so the same action looks similar regardless
    of distance from camera or body size.
    """
    frames = coords.shape[0]
    coords_3d = coords.reshape(frames, 25, 3)

    spine_base = coords_3d[:, 0, :]       # joint1 = SpineBase
    spine_shoulder = coords_3d[:, 20, :]  # joint21 = SpineShoulder

    torso_length = np.linalg.norm(spine_shoulder - spine_base, axis=1, keepdims=True)
    torso_length = np.clip(torso_length, 1e-3, None)

    centered = coords_3d - spine_base[:, np.newaxis, :]
    scaled = centered / torso_length[:, np.newaxis, :]

    return scaled.reshape(frames, 75)

def skeleton_to_sequence(coords, target_frames=64):
    """Resamples a variable-length clip to a fixed number of frames."""
    frames, n_features = coords.shape
    if frames < 2:
        return None
    old_idx = np.linspace(0, frames - 1, frames)
    new_idx = np.linspace(0, frames - 1, target_frames)
    resampled = np.zeros((target_frames, n_features), dtype=np.float32)
    for f in range(n_features):
        resampled[:, f] = np.interp(new_idx, old_idx, coords[:, f])
    return resampled

def add_motion_features(seq):
    """Position + velocity only - acceleration dropped, too noisy from double-differencing."""
    velocity = np.diff(seq, axis=0, prepend=seq[0:1])
    return np.concatenate([seq, velocity], axis=1)

import glob
import numpy as np

chunk_files = sorted(glob.glob("dataset_chunks/*.npz"))
print(f"Total chunks available: {len(chunk_files)}")

N_CHUNKS_TO_USE = 28
np.random.seed(42)
selected_chunks = list(np.random.choice(chunk_files, N_CHUNKS_TO_USE, replace=False))

X_parts, y_parts, meta_parts = [], [], []
for cf in selected_chunks:
    data = np.load(cf, allow_pickle=True)
    X_parts.append(data["X"])
    y_parts.append(data["y"])
    meta_parts.extend(data["meta"])

X = np.concatenate(X_parts, axis=0)
y = np.concatenate(y_parts, axis=0)
meta = meta_parts
del X_parts, y_parts

print(f"Final dataset: X={X.shape}, y={y.shape}")
print("Any NaN?", np.isnan(X).any())

import numpy as np
import os

CHUNK_SIZE = 2000
os.makedirs("dataset_chunks", exist_ok=True)

all_files = glob.glob("etri_csv_data/*.csv")
print(f"Total files: {len(all_files)}")

chunk_X, chunk_y, chunk_meta = [], [], []
chunk_idx = 0
skipped = 0

for i, path in enumerate(all_files):
    info = parse_filename(path)
    if info is None:
        skipped += 1
        continue
    action, person, group, camera = info
    try:
        coords = load_skeleton_csv_clean(path)
        if np.isnan(coords).any() or np.isinf(coords).any():
            skipped += 1
            continue
        coords_norm = normalize_skeleton(coords)
        seq = skeleton_to_sequence(coords_norm)
        if seq is None or np.isnan(seq).any():
            skipped += 1
            continue
        seq = add_motion_features(seq).astype(np.float32)
        if np.isnan(seq).any():
            skipped += 1
            continue
        chunk_X.append(seq)
        chunk_y.append(action)
        chunk_meta.append({"person": person, "group": group, "camera": camera})
    except Exception:
        skipped += 1

    if len(chunk_X) >= CHUNK_SIZE or i == len(all_files) - 1:
        np.savez_compressed(
            f"dataset_chunks/chunk_{chunk_idx:04d}.npz",
            X=np.array(chunk_X, dtype=np.float32),
            y=np.array(chunk_y),
            meta=chunk_meta
        )
        print(f"Saved chunk {chunk_idx} ({len(chunk_X)} samples) - processed {i+1}/{len(all_files)}, skipped {skipped}")
        chunk_idx += 1
        chunk_X, chunk_y, chunk_meta = [], [], []  # free memory

print("Done building chunks.")

def normalize_features_inplace(X, n_position_features=75):
    pos_view = X[:, :, :n_position_features]
    vel_view = X[:, :, n_position_features:]

    pos_mean, pos_std = pos_view.mean(), pos_view.std()
    vel_mean, vel_std = vel_view.mean(), vel_view.std()

    pos_view -= pos_mean
    pos_view /= (pos_std + 1e-8)
    vel_view -= vel_mean
    vel_view /= (vel_std + 1e-8)

    return X, (pos_mean, pos_std, vel_mean, vel_std)

X_norm, norm_stats = normalize_features_inplace(X)
assert not np.isnan(X_norm).any()
print("X_norm shape:", X_norm.shape)

N_CHUNKS_TO_USE = 14

subprocess.run(["bash", "-c", "cat /proc/meminfo | grep MemTotal"], check=False)

import glob
import numpy as np

chunk_files = sorted(glob.glob("dataset_chunks/*.npz"))
print(f"Total chunks available: {len(chunk_files)}")

N_CHUNKS_TO_USE = 28
np.random.seed(42)
selected_chunks = list(np.random.choice(chunk_files, N_CHUNKS_TO_USE, replace=False))

X_parts, y_parts, meta_parts = [], [], []
for cf in selected_chunks:
    data = np.load(cf, allow_pickle=True)
    X_parts.append(data["X"])
    y_parts.append(data["y"])
    meta_parts.extend(data["meta"])

X = np.concatenate(X_parts, axis=0)
y = np.concatenate(y_parts, axis=0)
meta = meta_parts
del X_parts, y_parts

print(f"Final dataset: X={X.shape}, y={y.shape}")
print("Any NaN?", np.isnan(X).any())

def normalize_features_inplace(X, n_position_features=75):
    pos_view = X[:, :, :n_position_features]
    vel_view = X[:, :, n_position_features:]

    pos_mean, pos_std = pos_view.mean(), pos_view.std()
    vel_mean, vel_std = vel_view.mean(), vel_view.std()

    pos_view -= pos_mean
    pos_view /= (pos_std + 1e-8)
    vel_view -= vel_mean
    vel_view /= (vel_std + 1e-8)

    return X, (pos_mean, pos_std, vel_mean, vel_std)

X_norm, norm_stats = normalize_features_inplace(X)
assert not np.isnan(X_norm).any()
print("X_norm shape:", X_norm.shape)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)
num_classes = len(le.classes_)

person_ids = np.array([m["person"] for m in meta])
unique_people = np.unique(person_ids)

np.random.seed(42)
np.random.shuffle(unique_people)
n_test_people = int(len(unique_people) * 0.2)
test_people = set(unique_people[:n_test_people])

test_mask = np.array([p in test_people for p in person_ids])
train_mask = ~test_mask

X_train, X_test = X_norm[train_mask], X_norm[test_mask]
y_train, y_test = y_encoded[train_mask], y_encoded[test_mask]

print("Train:", X_train.shape, "Test:", X_test.shape)

del X, X_norm
import gc
gc.collect()

def augment_skeleton_batch(X_batch, noise_std=0.02, scale_range=0.1):
    X_aug = X_batch.copy()
    noise = np.random.normal(0, noise_std, X_aug.shape)
    scale = 1.0 + np.random.uniform(-scale_range, scale_range, (X_aug.shape[0], 1, 1))
    X_aug = X_aug * scale + noise
    return X_aug

import tensorflow as tf

class AugmentedDataGen(tf.keras.utils.Sequence):
    def __init__(self, X, y, batch_size=32):
        self.X, self.y, self.batch_size = X, y, batch_size

    def __len__(self):
        return int(np.ceil(len(self.X) / self.batch_size))

    def __getitem__(self, idx):
        batch_X = self.X[idx*self.batch_size:(idx+1)*self.batch_size]
        batch_y = self.y[idx*self.batch_size:(idx+1)*self.batch_size]
        return augment_skeleton_batch(batch_X), batch_y

train_gen = AugmentedDataGen(X_train, y_train, batch_size=32)

from tensorflow.keras import layers, models, optimizers

def build_temporal_classifier_v2(input_shape, num_classes):
    inputs = layers.Input(shape=input_shape)

    x = layers.Conv1D(96, kernel_size=5, activation="relu", padding="same",
                       kernel_regularizer=tf.keras.regularizers.l2(1e-4))(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Conv1D(192, kernel_size=5, activation="relu", padding="same",
                       kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Conv1D(384, kernel_size=3, activation="relu", padding="same",
                       kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Conv1D(384, kernel_size=3, activation="relu", padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.GlobalAveragePooling1D()(x)

    x = layers.Dense(384, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(192, activation="relu")(x)
    x = layers.Dropout(0.4)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)

    model = models.Model(inputs, outputs)
    model.compile(
        optimizer=optimizers.Adam(learning_rate=1e-3, clipnorm=1.0),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

clf = build_temporal_classifier_v2(X_train.shape[1:], num_classes)
clf.summary()

from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weight_dict = dict(zip(np.unique(y_train), class_weights))

history = clf.fit(
    train_gen,
    validation_data=(X_test, y_test),
    epochs=100,
    class_weight=class_weight_dict,
    callbacks=[
        tf.keras.callbacks.TerminateOnNaN(),
        tf.keras.callbacks.EarlyStopping(patience=15, restore_best_weights=True),
        tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=5, min_lr=1e-6)
    ],
    verbose=1
)

import pickle
import json
import os
import shutil
from sklearn.metrics import classification_report, confusion_matrix

os.makedirs("saved_results", exist_ok=True)

clf.save("saved_results/etri_action_classifier.keras")
print("Model saved in Keras format")

model_pkl_data = {
    "architecture_json": clf.to_json(),
    "weights": clf.get_weights(),
    "input_shape": X_train.shape[1:],
    "num_classes": num_classes,
}
with open("saved_results/model.pkl", "wb") as f:
    pickle.dump(model_pkl_data, f)
print("Model saved as .pkl (architecture + weights)")

history_dict = history.history
with open("saved_results/training_history.pkl", "wb") as f:
    pickle.dump(history_dict, f)
with open("saved_results/training_history.json", "w") as f:
    json.dump(history_dict, f, indent=2)
print("Training history saved")

y_pred_probs = clf.predict(X_test)
y_pred = y_pred_probs.argmax(axis=1)

report = classification_report(
    y_test, y_pred,
    target_names=[f"A{c:03d}" for c in le.classes_],
    output_dict=True,
    zero_division=0
)

test_results = {
    "y_true": y_test,
    "y_pred": y_pred,
    "y_pred_probs": y_pred_probs,
    "class_labels": le.classes_,
    "classification_report": report,
    "confusion_matrix": confusion_matrix(y_test, y_pred),
}
with open("saved_results/test_results.pkl", "wb") as f:
    pickle.dump(test_results, f)
print("Test results saved")

with open("saved_results/label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

with open("saved_results/normalization_stats.pkl", "wb") as f:
    pickle.dump({"norm_stats": norm_stats}, f)
print("Label encoder + normalization stats saved")

print("\nAll files in saved_results/:")
print(os.listdir("saved_results"))

drive_output_dir = "/content/drive/MyDrive/etri_model_results"
shutil.copytree("saved_results", drive_output_dir, dirs_exist_ok=True)
print(f"All results copied to {drive_output_dir}")
print(os.listdir(drive_output_dir))